const GITHUB_AUTH_TOKEN = "LGmqvqqZFnhZHrG7IlzEiVi7S4zdvl4ZRXk0"
const BOT_NUMBER = "94740433291"
const SESSION_ID = "PRABATH-MD~CeIhEThZ#lSPJ-lMbJUIZu5p0fkjFSeX8E_rE17mvPXlwlIkBxY8"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
